### ISSUE TITLE
Not compatible with amazon fire hd 8..

### ISSUE THREAD

**Issue by WindowsUltra32** [TeamJCD/JoyConDroid#73]
Can you add compatability for this OS or is it Android only?

**Comment by Cyphs** [comment]
Did you even read the guide?

**Comment by WindowsUltra32** [comment]
No, why? Is it because you guys don't ever plan on adding compatibility for it?

**Comment by WindowsUltra32** [comment]
You guys really won't make an amazon fire hd 8 version for this? I ain't wasting money on a physical amiibo! so I better see some compatability added. Heck, talk to the other devs about it, see what they think!

**Comment by Rayjacker** [comment]
RTFM instead of begging, it's compatible with any Android (FireOS is based on Android, there should be *no* issue) device that supports : 

- Getting rooted
- Bluetooth HID profile
- HID_DEV_MTU_SIZE=512 for Amiibo support.

Also, there have been [10](https://www.gsmarena.com/results.php3?sQuickSearch=yes&sName=fire%20hd%208) devices released under the "Fire HD 8" name, be more specific. Depending on your tablet, it may get LineageOS support, check XDA for your model.
